spring:
  application:
    name: im
  profiles:
    active: client

  redis:
    host: amos.wang
    database: 8
    port: 1998

server:
  port: 8080

im:
  port: 8090
  host: localhost

logging:
  pattern:
    console: '%green(%-5level) %highlight([%thread]) %magenta(${PID}) %cyan(%logger) - %msg%n'