spring:
  application:
    name: im

  redis:
    host: amos.wang
    database: 8
    port: 1998

server:
  port: 8080

im:
  port: 8090
  host: localhost
  ws_domain: ${IM_WS_DOMAIN:}

logging:
  pattern:
    console: '%green(%-5level) %highlight([%thread]) %magenta(${PID}) %cyan(%logger) - %msg%n'